# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0020_auto_20171116_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
